# frozen_string_literal: true
# Generated by the protocol buffer compiler. DO NOT EDIT!
# source: message.proto

require 'google/protobuf'

# Serialized descriptor for protobuf
descriptor_data = "\n\rmessage.proto\x12\nmessage.v1\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2Q\n\x0eMessageService\x12?\n\x06Health\x12\x19.message.v1.HealthRequest\x1a\x1a.message.v1.HealthResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Grpc
  module MessagePb
    module Message
      module V1
        HealthRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("message.v1.HealthRequest").msgclass
        HealthResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("message.v1.HealthResponse").msgclass
      end
    end
  end
end