# frozen_string_literal: true
# Generated by the protocol buffer compiler. DO NOT EDIT!
# Source: message.proto for package 'message.v1'

require 'grpc'
require_relative 'message_pb'

module Grpc
  module MessageServicesPb
    module Message
      module V1
        module MessageService
          class Service
            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'message.v1.MessageService'

            # Fully qualified message class names
            rpc :Health,
                Grpc::MessagePb::Message::V1::HealthRequest,
                Grpc::MessagePb::Message::V1::HealthResponse
          end

          # Stub for client usage
          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end